name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.2.12 [CE|EE|ECE 2.4.0-2.4.7] 17 Aug 2024
          tag_name: 1.2.12
          body: |-
            ### softcommerce/module-profile-config [1.2.12]
            - **Compatibility**: Introduce support for Magento 2.4.7 [#4]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
