name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.2.13 [CE|EE|ECE 2.4.0-2.4.7] 27 Sep 2024
          tag_name: 1.2.13
          body: |-
            ### softcommerce/module-profile-config [1.2.13]
            - **Fix**: Apply a fix where profile config scope writer saves value as array opposed to serialised data [#29]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
